name: Tests

on:
  push:
  schedule:
    - cron: "0 15 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[testing]
    - name: Test with pytest
      run: |
        python -m pytest
    - name: Coverage with coveralls
      run: |
        python -m pip install coveralls
        python -m coveralls
      env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
